version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar-scanner
    depends_on:
      - sonarqube
    environment:
      SONAR_HOST_URL: "http://sonarqube:9000"
      SONAR_TOKEN: "squ_4a2201a5e0a4e66610988d60c8b5dcaecdc8d608"
    volumes:
      - .:/usr/src

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: